/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#e9ddff",
        "inverse-surface": "#32302e",
        "on-primary-fixed-variant": "#6b3836",
        "on-surface": "#1d1b19",
        "on-background": "#1d1b19",
        "tertiary-fixed-dim": "#d1bcff",
        "on-secondary": "#ffffff",
        "primary-container": "#ffb7b2",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f5f0ec",
        "surface-container": "#f3ede9",
        "on-primary": "#ffffff",
        "tertiary": "#665490",
        "surface-container-high": "#ede7e3",
        "primary-fixed-dim": "#fcb4b0",
        "primary-fixed": "#ffdad7",
        "surface-variant": "#e7e1de",
        "surface-container-low": "#f8f2ef",
        "tertiary-container": "#d3bfff",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#9ecede",
        "on-secondary-fixed-variant": "#1a4d5a",
        "secondary-fixed": "#baeafa",
        "on-tertiary-fixed-variant": "#4e3d77",
        "primary": "#874f4c",
        "on-primary-container": "#7b4542",
        "error-container": "#ffdad6",
        "outline": "#847372",
        "surface-container-highest": "#e7e1de",
        "on-secondary-fixed": "#001f27",
        "inverse-primary": "#fcb4b0",
        "surface-bright": "#fef8f4",
        "on-tertiary-fixed": "#220e49",
        "on-secondary-container": "#3a6977",
        "surface-dim": "#ded9d5",
        "outline-variant": "#d7c2c0",
        "error": "#ba1a1a",
        "background": "#fef8f4",
        "surface": "#fef8f4",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#524342",
        "secondary": "#356572",
        "on-tertiary-container": "#5c4a85",
        "surface-tint": "#874f4c",
        "on-tertiary": "#ffffff",
        "secondary-container": "#b7e7f7",
        "on-primary-fixed": "#360e0d"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "80px",
        "base": "8px",
        "xs": "4px",
        "gutter": "24px",
        "sm": "12px",
        "md": "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "lg": "48px"
      },
      fontFamily: {
        "caption": ["Quicksand"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-md": ["Quicksand"],
        "label-md": ["Quicksand"],
        "body-lg": ["Quicksand"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-xl": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "caption": ["12px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "1.3", "fontWeight": "800" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "500" }],
        "label-md": ["14px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "800" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "800" }],
        "headline-xl": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "900" }]
      }
    }
  },
  plugins: [],
}
